### ISSUE TITLE
How do i add more plugins if I want to

### ISSUE THREAD

**Issue by Vaimer9** [artart222/CodeArt#10]
Can i use multiple managers like `Plug` as well?? If so how?

**Comment by Vaimer9** [comment]
I get this error whenever I press `i`

**Comment by artart222** [comment]
I don't know about multiple plugin manager. If it work on normal NeoVim it will work on CodeArt as well. Can I ask you why you want to do that?

**Comment by Vaimer9** [comment]
I wanted To add https://github.com/andweeb/presence.nvim to my config for Discord RPC. I had this in my earlier init file and this was the one feature that wasn't included

**Comment by Vaimer9** [comment]
Till now I haven't been able to make it work, partially because I don't understand lua scripts and earlier I did everything in .vim files

**Comment by MedzsikT** [comment]
You can add more plugins by just `use { 'example/plugin' } in plugins.lua which is located in ~/.config/nvim/lua/

**Comment by artart222** [comment]
You can  use vim scripts in lua files directly with vim.cmd('vimscript command') or you can use multiline line vimscripts like this

vim.cmd
[[
vimscript command
vimscript command
]]

**Comment by Vaimer9** [comment]
Thanks For the advice! although I already knew the vim.cmd statement, I wasn't aware of use { ___, ___ }, it seems that the plugin just isn't working with CodeArt :(
