### ISSUE TITLE
Telescope doesn't seem to work.

### ISSUE THREAD

**Issue by sleeperzjf** [artart222/CodeArt#11]
Machine: Windows 10 
After I install this setup according to README, then I run the command `:PackerSync`.
![image](https://user-images.githubusercontent.com/65698607/139682701-4f74f850-db09-413b-bb13-b50bf991dd39.png)

**Comment by MedzsikT** [comment]
Do you want to update CodeArt?

**Comment by sleeperzjf** [comment]
Turns out I didn't have `make` installed. MY BAD. It works fine.

**Comment by artart222** [comment]
So I must add make to installer\window.p. But I have problem with these two plugins. Even I have make. I'm sure telescope-media-files didn't work on windows but I don't know about telescope-fzf-native

**Comment by sleeperzjf** [comment]
Can you install `ueberzug` successfully on your windows machine?
I can't and I think that's the reason why telescope-media-files didn't work on windows.
I used to use ueberzug and ranger on Linux, and it worked.

**Comment by artart222** [comment]
No, Even you can't install it on all linux. You can install ueberzug just if you have x11.

**Comment by artart222** [comment]
You are right telescope-fzf-native will work on windows. I will add it again

**Comment by dineshKumar777** [comment]
@artart222 I am getting following error for telescope fzf on fresh installation
![image](https://user-images.githubusercontent.com/21097695/154821877-4e9900dd-ab6f-4264-81e6-53fec85b007c.png)
