### ISSUE TITLE
LSP doesn't seem to work

### ISSUE THREAD

**Issue by sleeperzjf** [artart222/CodeArt#12]
Machine: window 10
When I press the shortcut to go to definition or rename or format codes , etc, it doesn't seem to do anything for me.
![image](https://user-images.githubusercontent.com/65698607/139684088-f8ed73df-6ac0-40e7-a2c9-0144a28ff879.png)

**Comment by sleeperzjf** [comment]
![image](https://user-images.githubusercontent.com/65698607/139684346-1207584c-3203-460d-a17f-8b576b3a4c91.png)
![image](https://user-images.githubusercontent.com/65698607/139684451-739e80cb-427c-4deb-a14a-4b31f1ce3104.png)

**Comment by artart222** [comment]
I will look at your problems, I only need time to finish my homework 🙂

**Comment by artart222** [comment]
I looked at your problem. I think the problem is clangd because when I was checking your problem I saw same problem on both windows and linux but I didn't see this problem in other programming languages.

**Comment by sleeperzjf** [comment]
![image](https://user-images.githubusercontent.com/65698607/139839126-2eb8b3f3-dac7-4d45-865b-c5a98a2b7347.png)
Is it because that the client isn't triggered?

**Comment by artart222** [comment]
Probably yes but just clangd doesn't attach. I don't know why ¯\_(ツ)_/¯ so I reopened your problem.

**Comment by artart222** [comment]
I don't know why but now after updating my plugins it is working

**Comment by artart222** [comment]
If you have problem please reopen issue.
