### ISSUE TITLE
Can We get like a list of all the commands that can be run like changing the theme and lsp commands

### ISSUE THREAD

**Issue by Vaimer9** [artart222/CodeArt#13]
i just want the theme change and lsp commands lol

**Comment by MedzsikT** [comment]
You can change themes with :colorscheme <installed_theme>
All the keybindings are listed in ~/.config/nvim/lua/maps.lua.

But here you go:
<Space>,  - diagnostic.goto_prev
<Space>; - diagnostic.goto_next
<Space>a - code action
<Leader(which is space by default)>gd - goto definition
<Space>f - formatting (formats code)
<Space>h - hover
<Space>m - rename
<Space>r - references
<Space>s - document symbol

**Comment by artart222** [comment]
I am working on writing wik for CodeArt

**Comment by Vaimer9** [comment]
thank you very much for immediate response on all of my issues, I made like 5 issues that day.
