### ISSUE TITLE
Can I use ccls for c++ language server?

### ISSUE THREAD

**Issue by LXYYY** [artart222/CodeArt#20]
Hi, I'm really impressed by the beautiful UI of codeart, good job! But talking about c++ language server, I prefer ccls instead clangd, is there any way I can use ccls instead of clangd?

**Comment by artart222** [comment]
You can install ccls manually and after that add this code block to end of lsp.lua
```lua
require'lspconfig'.ccls.setup {
    capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
}
```

**Comment by artart222** [comment]
This must be lsp.lua after modifications:
```lua
local lsp_installer = require("nvim-lsp-installer")
lsp_installer.on_server_ready(function(server)
   local opts = {}
   server:setup {
     capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
   }
   vim.cmd [[ do User LspAttachBuffers ]]
end)

require'lspconfig'.ccls.setup {
    capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
}
```

**Comment by LXYYY** [comment]
I modified lsp.lua as you said, but nothing happened. I use ccls always, my ccls installation is correct. Is there anything I need to do after I modified the file? By the way, I just tried to use coc.nvim along with codeart, and set coc.nvim language server to ccls, I can get code suggestions from ccls correctly, but syntax highlighting not working.

**Comment by artart222** [comment]
I don't know about syntax highlighting with coc but you can install treesitter for cpp with `:TSInstall cpp` after that restart NeoVim you well get much better syntax highlighting with it.

**Comment by artart222** [comment]
Was your problem solved? And if yes with treesitter of coc?

**Comment by artart222** [comment]
I am closing this issue because of no response in 7 days.

**Comment by artart222** [comment]
If you have a problem just put comment I will reopen it
