### ISSUE TITLE
error on nvim startup

### ISSUE THREAD

**Issue by TheYanusz** [artart222/CodeArt#22]
Hi, Im using Gentoo so i installed all packages from installer script but I still cannot use CodeArt properly. The issue is some lua errors and "Not an editor command: EnableWhitespace" and DisableWhitespace. Any ideas? Thanks in advance.

`Error detected while processing function matchup#loader#bufwinenter[4]..matchup#loader
#init_buffer[5]..matchup#ts_engine#is_enabled[4]..<SNR>38_forward:
line    1:
E5108: Error executing lua vim.lua:64: ...m/site/pack/packer/start/vim-matchup/lua/tre
esitter-matchup/internal.lua:192: '=' expected near 'continue'
Error detected while processing function matchup#loader#bufwinenter[4]..matchup#loader
#init_buffer[15]..matchup#ts_engine#is_hl_enabled[4]..<SNR>38_forward:
line    1:
E5108: Error executing lua vim.lua:64: ...m/site/pack/packer/start/vim-matchup/lua/tre
esitter-matchup/internal.lua:192: '=' expected near 'continue'
Error in packer_compiled: ...te/pack/packer/start/packer.nvim/lua/packer/load.lua:83:
Vim:E492: Not an editor command: EnableWhitespace
Please check your config for correctness
Error in packer_compiled: ...te/pack/packer/start/packer.nvim/lua/packer/load.lua:110:
 Vim:E492: Not an editor command: EnableWhitespace
Please check your config for correctness
Error in packer_compiled: ...te/pack/packer/start/packer.nvim/lua/packer/load.lua:83:
Vim:E492: Not an editor command: DisableWhitespace`

These are the errors mentioned above

**Comment by artart222** [comment]
I don't know why this is happening.

**Comment by artart222** [comment]
I installed CodeArt on new virtual machine and I don't have any problem with it

**Comment by TheYanusz** [comment]
OK I'll try find a solution, I'll comment a solution if I find one, maybe lua recompilation will do the job.

**Comment by artart222** [comment]
Ok, thanks

**Comment by ciiiii** [comment]
Same problem on m1 Mac

**Comment by artart222** [comment]
Did you ran `:PackerSync` after first startup of CodeArt?

**Comment by TheYanusz** [comment]
To be honest I broke my Gentoo install, needed to reinstall and it worked for me.

**Comment by Israel-Laguan** [comment]
This seem related to #17 , can you try https://github.com/artart222/CodeArt/issues/17#issuecomment-962805575 ?

```sh
# run nvim
:PackerInstall
:PackerCompile
:q! # Exit
# run nvim
:PackerSync
:q!
# run nvim
``

**Comment by TheYanusz** [comment]
OK it worked on Fedora Im back on Gentoo and the error persists even after using 
`:PackerSync`

**Comment by TheYanusz** [comment]
FIX:
compile neovim with this source code: https://github.com/neovim/neovim/archive/refs/tags/stable.tar.gz
