### ISSUE TITLE
Set colorscheme?

### ISSUE THREAD

**Issue by hartzan** [artart222/CodeArt#25]
Hi,

how can I define some other colorscheme? I am trying to use "RRethy/nvim-base16" and I put it into user_settings.lua and it was installed ok. I can use those themes if I type :colorscheme base16-chalk for example. But if I put the same scheme to theme.lua:vim.cmd("base16-chalk"), nvim says:

Error detected while processing /home/user/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/user/.config/nvim/lua/theme.lua:15: Vim:E492: Not an editor command: base16-chalk

I think that it used to work before your latest commit?

**Comment by artart222** [comment]
I tried same thing you said but tried of nvim-base16 I used material.nvim and set colorscheme in theme.lua:vim.cmd("material"). It is working correctly. I don't know why you have problem

**Comment by hartzan** [comment]
Hi, 
I just noticed that in theme.lua you have to have:vim.cmd("colorscheme base16-chalk"), sorry about that :-)
It's working now. How can I set theme in user_settings so I don't have to edit theme.lua again after updating codeart?

**Comment by artart222** [comment]
Just add vim.cmd("colorscheme base16-chalk") in user_settings.lua. It will choose base16 theme instead of theme of theme.lua

**Comment by hartzan** [comment]
Thanks a lot!!
