### ISSUE TITLE
add clangd arguments

### ISSUE THREAD

**Issue by Matteoverzotti** [artart222/CodeArt#26]
So I want to use C++ with Clangd. But whenever I try to autocomplete a predefined function, clangd auto-includes the necessary header/library. 
I know I can disable that by adding flags to clangd but I can't find where to put those flags.

**Comment by artart222** [comment]
I will work on feature to customize language servers in upcoming days

**Comment by artart222** [comment]
You can put something like this in your user_settings.lua

**Comment by artart222** [comment]
```lua
require'lspconfig'.clangd.setup {
  cmd = { "clangd", "your_flag" },
  capabilities = require("cmp_nvim_lsp").update_capabilities(vim.lsp.protocol.make_client_capabilities())
}

```

**Comment by artart222** [comment]
If you have problem just put comment here I will reopen issue

**Comment by artart222** [comment]
And another thing. For using this method for adding flag you must install clangd with normal method not with built in LspInstall clangd method

**Comment by rajtendulkar** [comment]
```
Error detected while processing /home/raj/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/raj/.config/nvim/lua/user_settings.lua:34: module 'lspconfig' not found:
        no field package.preload['lspconfig']
        no file './lspconfig.lua'
        no file '/usr/share/luajit-2.1.0-beta3/lspconfig.lua'
        no file '/usr/local/share/lua/5.1/lspconfig.lua'
        no file '/usr/local/share/lua/5.1/lspconfig/init.lua'
        no file '/usr/share/lua/5.1/lspconfig.lua'
        no file '/usr/share/lua/5.1/lspconfig/init.lua'
        no file './lspconfig.so'
        no file '/usr/local/lib/lua/5.1/lspconfig.so'
        no file '/usr/lib/x86_64-linux-gnu/lua/5.1/lspconfig.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        /home/raj/.config/nvim/lua/user_settings.lua:34: in main chunk
        [C]: in function 'require'
        /home/raj/.config/nvim/lua/plugins.lua:2: in main chunk
        [C]: in function 'require'
        /home/raj/.config/nvim/init.lua:3: in main chunk
Press ENTER or type command to continue

```

This is the error I am getting. I cannot run `PackerSync` after I add that in user_settings.

**Comment by artart222** [comment]
For now you can't change default plugins settings in user_settings.lua. You must add it to lsp.lua file.

**Comment by rajtendulkar** [comment]
Thanks that solved the problem. 
i see an error when I open nvim :
`Client 1 quit with exit code 1 and signal 0`
Also goto declaration or goto implementation doesn't work.

**Comment by artart222** [comment]
It seems that error is for your pyright

**Comment by artart222** [comment]
You probably opened a place with lots of files and because of that pyright can't index those files

**Comment by rajtendulkar** [comment]
I uninstalled all the servers and still no improvement. Is there a way, I can debug this?
