### ISSUE TITLE
making background transparent doesn't work

### ISSUE THREAD

**Issue by rinqtmith** [artart222/CodeArt#27]
Hey,

I cannot make full background transparent. It works partial.
WSL2 in Windows 10.

![image](https://user-images.githubusercontent.com/46543046/140622667-157371b8-a034-48d3-b6b8-21cc887c607d.png)

**Comment by artart222** [comment]
You must alos set your terminal transparent

**Comment by artart222** [comment]
If setting terminal transparent fixed your problem please close this issue

**Comment by rinqtmith** [comment]
Adding `vim.cmd('highlight EndOfBuffer guibg=none')` worked. Terminal was transparent.

**Comment by artart222** [comment]
theme.lua has this line in it.
