### ISSUE TITLE
Not an editor Command (Debain)

### ISSUE THREAD

**Issue by Decapitater** [artart222/CodeArt#28]
PackerInstall 
Not an Editor Command

**Comment by Decapitater** [comment]
@artart222

**Comment by artart222** [comment]
Neovim 0.5 is not in apt repos. You probably installed 0.4.4. CodeArt will not work because of NeoVim version. You can download NeoVim 0.5 binary file here https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz

**Comment by Decapitater** [comment]
Alright i will try and report further

**Comment by Decapitater** [comment]
thnx
