### ISSUE TITLE
ct mapping conflicts with default ct behaviour (how to un map in lua?)

### ISSUE THREAD

**Issue by paulgrove** [artart222/CodeArt#29]
CodeArt remaps `ct` to `:CommentToggle<CR>`, however, I commonly use ct for its default behaviour - change to `<char>`.

Please can you advise how I can remove this mapping via user_settings? or consider changing CommentToggle to `<leader>ct`

Many thanks for this project, I am enjoying using it.

**Comment by paulgrove** [comment]
I also have an issue with `<S-j>` which is usually Join Line - again I would want to unmap this, and probably all of the Resize mappings.

**Comment by paulgrove** [comment]
Another suggestion for `nt` to change to `<leader>nt` for nerd tree - this mapping makes using `n` for next while searching cumbersome.

**Comment by artart222** [comment]
You can unmap in lua with `vim.api.nvim_del_keymap(mode, "keys")`
For example you can unmap ct in visual mode with
```lua
vim.api.nvim_del_keymap(v, "ct")
```

**Comment by paulgrove** [comment]
Thanks! that does the trick for me.

I really like your nvim configuration and this project is fun.  I didn't want to step on your preferred key mappings and I am happy that I can just unmap them!

**Comment by paulgrove** [comment]
Hi just noticed that `vim.api.nvim_del_keymap`  doesn't work on a fresh startup of nvim.

If I have such a line in my user_settings.lua I get the following error:

```
Error detected while processing /home/pgrove839/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /home/pgrove839/.config/nvim/lua////user_settings.lua:31: E31: No such mapping
Press ENTER or type command to continue
```

**Comment by artart222** [comment]
It's seems it will work on some of mappings

**Comment by artart222** [comment]
But you can remap some a mapping instead of deleting it. For example for your join line problem you can map like this ```lua map("n", "<S-j>", ":join")```

**Comment by paulgrove** [comment]
I will test again on Monday, thanks for the feedback

**Comment by paulgrove** [comment]
@artart222 thanks for the suggestion, but I did not like the idea of reverse engineering the original mapping for each which I want to revert.
I did some research however and I have found a solution, I think that any lua that invokes vimL gets queued in the event system, and therefore at the time that `nvim_del_keymap` is invoked the `nvim_set_keymap` commands from maps.lua have not yet been actioned.
Instead I have wrapped all my personal key mappings in user_settings.lua into a `vim.schedule_wrap` which like this:

```
vim.schedule_wrap(function()
    map('n', '<C-p>', ':Telescope find_files<CR>')
    map('n', '<C-r>', ':Telescope live_grep<CR>')

    map('n', '<C-t>', ':ToggleTerm<CR>')
    map('t', '<C-t>', '<Esc><Cmd>exe v:count1 . "ToggleTerm"<CR>')

    vim.api.nvim_del_keymap("n", "ct")
    vim.api.nvim_del_keymap("v", "ct")

    vim.api.nvim_del_keymap('n', '<S-j>')
    vim.api.nvim_del_keymap('n', '<S-k>')
    vim.api.nvim_del_keymap('n', '<S-l>')
    vim.api.nvim_del_keymap('n', '<S-h>')

    map('n', '<A-H>', ':call ResizeLeft(3)<CR><Esc>')
    map('n', '<A-L>', ':call ResizeRight(3)<CR><Esc>')
    map('n', '<A-K>', ':call ResizeUp(1)<CR><Esc>')
    map('n', '<A-J>', ':call ResizeDown(1)<CR><Esc>')

    vim.api.nvim_del_keymap('n', 'nt')

    map('n', 'gd', ':lua vim.lsp.buf.definition()<CR>')
    map('n', '<leader>nt', ':NvimTreeToggle<CR>')

    map("n", "<leader>//", ":CommentToggle<CR>")
    map("v", "<leader>//", ":'<,'>CommentToggle<CR>")

    map('n', '<leader>z', ':TZFocus<CR>')
end)
```

I believe this wait for the next eventloop where it is safe to execute vimL.

I considered wrapping the entire of `require('user_settings')` in a `vim.schedule_wrap`, but it didn't work as I expected.  If you are better at lua than me perhaps you could look into doing it like this so that care need not be needed by users modifying their `user_settings.lua`.  Otherwise can I suggest that the example `user_settings.lua` include an example of using `vim.schedule_wrap` similar to the code I posted above.

**Comment by artart222** [comment]
I tried your example but I didn't know why it didn't work -_-
