### ISSUE TITLE
[TESTING CODE ON OSX] 

### ISSUE THREAD

**Issue by Sable-20** [artart222/CodeArt#3]
May i recommend trying to use github actions or something like travis CI to run it and if it errors you know somethings wrong. ;)

**Comment by artart222** [comment]
I doesn't ever use github action. I think I must try it

**Comment by artart222** [comment]
So, I looked at this but I want full testing like all plugins work or for example something weird will not happen if you press something.

**Comment by artart222** [comment]
I am currently testing CodeArt for windows and some linux distributions with different package managers  in virtual machine.

**Comment by artart222** [comment]
I want similar testing

**Comment by Israel-Laguan** [comment]
I tested it on Mac Catalina 15.7, Intel chip (MBP 2019):

![image](https://user-images.githubusercontent.com/36519478/140682811-356aacb5-b545-4c3b-a406-aed967ebee0d.png)

Calling `python3 install.py`
![image](https://user-images.githubusercontent.com/36519478/140682843-6c0ebf17-56cc-4e45-93bd-fab467dce4b2.png)

A lot of installation going on:
![image](https://user-images.githubusercontent.com/36519478/140682920-44f59d9e-041f-454c-87f7-00af2fd9637a.png)

Had to put my password at a certain point:
![image](https://user-images.githubusercontent.com/36519478/140683314-4f73950b-94e5-4dcf-9908-203c941c6c5f.png)

Failed while trying to download font
![image](https://user-images.githubusercontent.com/36519478/140683478-c28f2813-6628-4603-9cdc-57fc7ced2627.png)

😢

**Comment by Israel-Laguan** [comment]
So I found a solution for the issue [HERE]()https://stackoverflow.com/a/13057751, applied and it succeeded!

![image](https://user-images.githubusercontent.com/36519478/140683771-c7a46253-297b-4213-a73f-d55fdb67f0e0.png)

**Comment by Israel-Laguan** [comment]
What else is needed to close this issue @artart222?

**Comment by artart222** [comment]
I added encoding line. I let this issue to be opened in case of more problem. I think there is no need to this issue anymore so I'm closing it.
