### ISSUE TITLE
Bug with `nvim-tree` and `nvim-cmp`

### ISSUE THREAD

**Issue by AlphaNecron** [artart222/CodeArt#32]
https://user-images.githubusercontent.com/57827456/141050300-e23ed514-5fa8-4243-b138-7d1916d78f72.mp4

**Comment by AlphaNecron** [comment]
Double-clicking or pressing enter the file on the tree will append a random string at the end of the file.

**Comment by artart222** [comment]
I don't know why this is happening. If someone can solve this problem please put the answer here

**Comment by bryant-the-coder** [comment]
is it working now??

**Comment by AlphaNecron** [comment]
Idk, using my own config atm.

**Comment by bryant-the-coder** [comment]
try using it back. and use nvimtree without toggleterm

**Comment by artart222** [comment]
I think the problem is fixed. If you have problem reopen issue.
