### ISSUE TITLE
LSP tsserver doesn't work on js files without a git repository

### ISSUE THREAD

**Issue by RimuCode** [artart222/CodeArt#33]
what can i do to make LSP recognize my js files? it doesn't if there's no git repository

![image](https://user-images.githubusercontent.com/68438095/141053616-e44f7b92-bf5e-4067-8aaa-75c6beaf962e.png)

**Comment by artart222** [comment]
tsserver will work if it find these items in directory you are working at it

**Comment by artart222** [comment]
"package.json", "tsconfig.json", "jsconfig.json", ".git"
