### ISSUE TITLE
PackerInstall is not a editor command on Windows

### ISSUE THREAD

**Issue by hugorplobo** [artart222/CodeArt#34]
Hi, I finished the installation on my Windows but when I try to run `:PackerInstall` I receive a "PackerInstall is not an editor command".

![image](https://user-images.githubusercontent.com/53958114/142966251-1948146b-b89c-41fb-a0e2-277c093290df.png)

I used all of the commands from the Windows installation section.

**Comment by artart222** [comment]
Open powershell and run this command:
```ps1
git clone https://github.com/wbthomason/packer.nvim "$env:LOCALAPPDATA\nvim-data\site\pack\packer\start\packer.nvim"
```

**Comment by artart222** [comment]
If it worked please close this issue

**Comment by hugorplobo** [comment]
I had already done that. I redid the installation and made sure I followed all the steps but I still can't get it to work.

**Comment by artart222** [comment]
By looking at screenshot I think the configs files are not in correct place. Is there any config file at `C:\Users\your_user\AppData\Local\nvim`

**Comment by artart222** [comment]
I don't know why but neovim config files are missing. Download repo replace nvim with config directory of repo and be sure new config directory name is nvim

**Comment by hugorplobo** [comment]
The script was moving the folder config inside the nvim folder, so I just deleted the config and manually copied the files. Thank you so much!

**Comment by nimeshmaharjan1** [comment]
> I don't know why but neovim config files are missing. Download repo and replace nvim directory with config directory of repo and be sure new config directory name is nvim

which nvim directory the AppData/Local/nvim directory or inside the nvim-data

**Comment by nimeshmaharjan1** [comment]
Im really confused

**Comment by ksaswin** [comment]
@nimeshmaharjan1 After cloning, you need to move everything within the cloned repo to `C:\Users\user_name\AppData\Local\nvim\`.
