### ISSUE TITLE
XDG config home spec error on install

### ISSUE THREAD

**Issue by erayaydin** [artart222/CodeArt#35]
Hello,

I'm trying to install CodeArt with `instal.py` but its try to create `~/.config/nvim` but my `$XDG_CONFIG_HOME` is `~/.local/etc`. `install.py` should use `$XDG_CONFIG_HOME` environment variable if its exists.

```
Moving configs
Traceback (most recent call last):
  File "/home/eray/Downloads/CodeArt/install.py", line 6, in <module>
    from installer import linux
  File "/home/eray/Downloads/CodeArt/installer/linux.py", line 164, in <module>
    main()
  File "/home/eray/Downloads/CodeArt/installer/linux.py", line 160, in main
    copy_configs(home_directory_address)
  File "/home/eray/Downloads/CodeArt/installer/linux.py", line 86, in copy_configs
    os.mkdir(home_directory_address + "/.config/nvim")
FileNotFoundError: [Errno 2] No such file or directory: '/home/eray/.config/nvim'
```

```
$ env | grep XDG_CONFIG_HOME
XDG_CONFIG_HOME=/home/eray/.local/etc
```

PS: previously its used `$XDG_CONFIG_HOME` when install `packer`.

```
...
Cloning into '/home/eray/.local/share/nvim/site/pack/packer/start/packer.nvim'...
...
```

**Comment by artart222** [comment]
Yeah, you are right. I will fix  it until sunday

**Comment by erayaydin** [comment]
Thanks for the comment. Please link this issue in commit (if possible). I'll re-install CodeArt after the update.

**Comment by artart222** [comment]
https://github.com/artart222/CodeArt/commit/c9085a0afdbb99fc5734d13162a3961f0f46239c

**Comment by erayaydin** [comment]
Thanks for your effort and commit 👍 I'll re-install CodeArt.
