### ISSUE TITLE
Not an editor command: Telescope

### ISSUE THREAD

**Issue by Animeshz** [artart222/CodeArt#38]
Any telescope keybind/command says not an editor command.

```
Error in packer_compiled: ...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:83: Vim:E492: Not an editor command: Telescope find_files find_comman
d=rg,--follow,--hidden,--files                                                                                                                             
Please check your config for correctness
```

Have done `:PackerSync` and I'm on latest tip of main branch.

Distro: Void Linux x86_64 (glibc)
nvim: NVIM v0.6.0 Release | LuaJIT 2.1.0-beta3

I'm new to nvim (specially configurations, so I tried to start using other's first), how can I help debugging this?

**Comment by artart222** [comment]
I changed some codes. Try `CodeArtUpdate` and reopen NeoVim and run `PackerSync` again. If problem solved  close this issue

**Comment by Animeshz** [comment]
No, still facing the same problem :eyes:

**Comment by Animeshz** [comment]
Its also weird, first time it autocompletes, but errors and then next time it doesn't (see attachment).

https://user-images.githubusercontent.com/26714676/145039249-d2a86bd6-adab-45dd-90ed-65bef939dcb1.mp4

**Comment by artart222** [comment]
You have wayland or X11?

**Comment by pvini07BR** [comment]
I'm having the same issue here on Arch Linux.

**Comment by xZeroW** [comment]
I got the same error, its been like this for almost 2 weeks

**Comment by xZeroW** [comment]
I don't know if this helps but I did some backtracking and found the latest Telescope working commit https://github.com/artart222/CodeArt/tree/90131ad42280973350208ff088d87d1800af1e29

**Comment by artart222** [comment]
I fixed it. Can some one double check it

**Comment by xZeroW** [comment]
Yep, works like a charm

I got this error on the first run:
![first-run](https://user-images.githubusercontent.com/14045316/145106757-c67fde59-37be-4ffb-a2c4-f2d17a4bd80d.png)
After running :PackerInstall & :PackerCompile seems to fix it, I don't know if that's supposed to be like that because we haven't run install & compile before

**Comment by artart222** [comment]
I changed some other settings and that errors are because of that because of that you always must run `PackerSync` after `CodeArtUpdate`. Thank you because of checking it

**Comment by artart222** [comment]
If you find a problem in the future, please open github issue so I can fix it
