### ISSUE TITLE
i don't see any snippet for javascript python or html

### ISSUE THREAD

**Issue by rimurimuh** [artart222/CodeArt#41]
I use to work in web development but i saw that there's snippets for java,lua,vimscript,etc but not for javascript,typescript or html i don't know if there's other languages that have the same problem, so i been reading other configs and haven't seen too much differences compared to CodeArt completion configs, for that reason i don't know what to do about it since i'm not too experienced on configuring nvim

here i don't see snippets for js or python

![image](https://user-images.githubusercontent.com/68438095/149639027-93c79457-8d3a-4db5-94a2-0db27bfac84c.png)
![image](https://user-images.githubusercontent.com/68438095/149639041-a032d59f-3fe9-4c0f-8a05-73c1fd5e8b20.png)

i correctly see snippets for java

![image](https://user-images.githubusercontent.com/68438095/149639075-02d5ec5e-031a-42af-8421-3805634b54de.png)
so cause of that i think luasnip works

i have lsp servers for all of those languages 

apologize if is a fool question

**Comment by artart222** [comment]
I will fix it within next 24 hours

**Comment by artart222** [comment]
Fixed

**Comment by artart222** [comment]
If you still have any problem please open issue so I can fix it
