### ISSUE TITLE
Why is Node Listed as a Dependency?

### ISSUE THREAD

**Issue by johnyenter-briars** [artart222/CodeArt#43]
Greetings - Love the Project! 

I currently use CodeArt on my Windows machine and loving it.

I went to install it on my Arch machine, and noticed that it installs node and npm related packages;

```
pack_manager_install(distro_name, list_of_apps, "npm", "npm", "npm", "npm", "npm14", "")
```

I use NVM to manage node versions, and I don't really want to worry about node version conflicts.

Is node (and/or a certain version) a hard and fast dependency for CodeArt? If not, I can just comment out that line in the installer. 

Thank you!

**Comment by artart222** [comment]
https://github.com/williamboman/nvim-lsp-installer#installation

**Comment by artart222** [comment]
It's for nvim-lsp-installer If you don't want to install node you must install language servers manually

**Comment by johnyenter-briars** [comment]
@artart222  - ok! That makes sense. I was able to test the installation on a test box, and confirmed that installing those dependencies did not mess with my NVM installation. Everything seems to be working just fine. Will close this Issue. 

Thank you for your help!
