### ISSUE TITLE
Everything is filled with `+prefix`

### ISSUE THREAD

**Issue by asm0dey** [artart222/CodeArt#44]
Right after installation, here is how the space menu looks:

![image](https://user-images.githubusercontent.com/1297282/149829205-e00797d1-4e5a-4129-8723-44d21cd051ab.png)

I believe that there should be something else

**Comment by artart222** [comment]
for now there is no mapping defined for which-key and because of that you have +prefix. I have school and a lot of homework but I will define key maps for which-key in next 3 days

**Comment by asm0dey** [comment]
Cool, thank you for the quick response!

**Comment by bryant-the-coder** [comment]
should i help?

**Comment by artart222** [comment]
Thanks, but it's almost finished and I'm changing a few other things at the same time so I must done it by my self

**Comment by bryant-the-coder** [comment]
l

**Comment by artart222** [comment]
Fixed it

**Comment by artart222** [comment]
I changed some mappings too. If you see any other problem please open issue.
