### ISSUE TITLE
No autocomplete for JavaScript.

### ISSUE THREAD

**Issue by iDCoded** [artart222/CodeArt#45]
![issue-image](https://user-images.githubusercontent.com/65074550/150407347-c4899c96-c5f3-4e8b-a9d2-092fc0f36358.png)
 I am not getting any autocomplete suggestions for my JavaScript code. 
I do have the Language server installed.

**Comment by artart222** [comment]
Unfortunately for javascript/typescript  you need to have root directory. I assumed you are using denols. For denols you need one of deno.json, deno.jsonc, tsconfig.json or .git file/directory in your root directory.
You can see all of language servers !(here)[https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#configurations]. You can find there what do you need for root directory

**Comment by artart222** [comment]
If you have any other problem please open issue

**Comment by bryant-the-coder** [comment]
For your info, you will need a .git file which can be acquired by running `git init` in the local repo. You will also need to add the language server in the file named lsp.lua if you want to. Or just create a new file in the plugins folder
