### ISSUE TITLE
warning: multiple different client offset_encodings detected for buffer, this is not supported yet

### ISSUE THREAD

**Issue by rajtendulkar** [artart222/CodeArt#46]
When  trying to jump to a function definition I get this error and the Vim does not jump.

`warning: multiple different client offset_encodings detected for buffer, this is not supported yet`

**Comment by artart222** [comment]
I know it's been long time since you opened an issue but this error is from coming from [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim/issues/428)

**Comment by artart222** [comment]
There is option to disable this error on some language servers but you can't do that in CodeArt. If you want you can install neovim-nightly and use CodeArt nightly branch and wait until neovim 0.7 release for using CodeArt main branch
