### ISSUE TITLE
Updating CodeArt will remove user CodeArt configs

### ISSUE THREAD

**Issue by artart222** [artart222/CodeArt#5]
Because :CodeArtUpdate will replace this repo configs directory with ~/.config/nvim it will completely remove users CodeArt configs
If anyone has idea to prevent this issue I will be happy to hear it

**Comment by MedzsikT** [comment]
Hi!
I wrote a bash script that does the thing, but it will replace ONLY maps.lua, but it can applied to all of the files.

# CodeArtUpdate.sh
`mkdir ~/.config/nvim.temp`
`mv ~/.config/nvim/lua/maps.lua ~/.config/nvim.temp/maps.lua`
`svn export --force https://github.com/artart222/CodeArt.git/trunk/configs/ ~/.config/nvim`
`mv ~/.config/nvim.temp/maps.lua ~/.config/nvim/lua/maps.lua`
`rmdir ~/.config/nvim.temp`

For me it's in ~/.config/nvim/

# settings.lua
Replace: `command CodeArtUpdate !svn export --force https://github.com/artart222/CodeArt.git/trunk/configs/ ~/.config/nvim`
With: `command CodeArtUpdate !./.config/nvim/CodeArtUpdate.sh // path to the bash script`

Note: Make sure that CodeArtUpdate.sh is runnable
It worked for me, hope it helps!

**Comment by artart222** [comment]
This is better than my approach but the problem is maybe the user added a plugin to CodeArt then updating CodeArt will remove his/her plugins. I was thinking to make some sort of user-settings.lua file but I don't know how to do that. Can you help to do this?

**Comment by MedzsikT** [comment]
I'm not really familiar with lua and with NeoVim API, but I will try my best. Do you have Discord?

**Comment by artart222** [comment]
I made a discord channel. discord.com/channels/904682355942375445

**Comment by MedzsikT** [comment]
You need to copy the servers invite link. In the top left corner, there is the name of the server, click it and there is an option "invite people".

**Comment by artart222** [comment]
https://discord.gg/mhy9aK9Qzp

**Comment by artart222** [comment]
Thanks for letting me know

**Comment by MedzsikT** [comment]
Updates on this on discord!

**Comment by artart222** [comment]
Fixed with https://github.com/artart222/CodeArt/commit/56789587689cb60c2dd4348a46f5e30f7357b18a
