### ISSUE TITLE
after installing CodeArt, packer not found error occuring

### ISSUE THREAD

**Issue by Waishnav** [artart222/CodeArt#50]
![image](https://user-images.githubusercontent.com/86405648/160238692-4cfb56a4-778c-4ce6-a2d6-a6d7ec376ca1.png)

Have a look at the screenshot above, so after running the install script, ```:PackerSync``` is not working

**Comment by artart222** [comment]
By the screenshot I guess you are using mac or a linux distro(probably a linux distro). Can you please tell what is your OS or distro. Which branch do you use. nightly or main?

**Comment by Waishnav** [comment]
its main and I'm using Linux and btw I've solved that issue by manually installing packer...
really appreciate your work dude amazing neovim config

**Comment by artart222** [comment]
Thanks. Probably it will be way more better in next week. Neovim milestone for 0.7 release is first of april whenever 0.7 come out I will merge nightly branch with main. It has around 50 more commits
