### ISSUE TITLE
move "CodeArt/configs/*" to CodeArt/*"

### ISSUE THREAD

**Issue by kraxli** [artart222/CodeArt#51]
moving `CodeArt/configs/lua/` to `CodArt/lua` and `CodeArt/configs/init.lua` to `CodeArt/init.lua` would allow for easier `git` integration like directly cloning into `~\.config\nvim`, working with `submodule`, tweaking a forked of the repo by the user, ...

**Comment by artart222** [comment]
I will do this but I need time

**Comment by artart222** [comment]
It's a while since I did this so I'm closing this issue. Thanks for your advice
