### ISSUE TITLE
Installation script fails in OpenSUSE

### ISSUE THREAD

**Issue by yoogui** [artart222/CodeArt#54]
There is some mistake in the installation script. I dont know about shell script, but there is some kind of trouble in the command for Zypper package manager to install the dependencies. I installe manually with `sudo zypper in _package_`
Maybe can you try to fix it.

**Comment by yoogui** [comment]
Ok, so the error is in the command `sudo zypper -n` from installation script, 
that actually do nothing.

Instead of mentioned the correct Zypper command is `zypper in [package]`
The dependencies for installation in OpenSUSE are the nexts:

`nodejs`
`gcc-c++`
`make`
`xclip`
`ripgrep`
`fd`
`wget`

**Comment by artart222** [comment]
I changed zypper command in installer and I guess it must work now. Thanks for opening issue.
