### ISSUE TITLE
Add additional plugins in user_settings.lua failed

### ISSUE THREAD

**Issue by jamestsay** [artart222/CodeArt#56]
Simply uncomment any plugin in user_settings does not load nvim properly. It failed on this call from .config/nvim/lua/plugins.lua
-- Install additional user plugins.
    for _, plugin in pairs(additional_plugins) do
      if type(plugin) == "string" then
        use({ plugin })
      else
        use({ table.unpack(plugin) })
      end
    end

**Comment by artart222** [comment]
I don't know why ```table.unpack()``` doesn't work but I fixed that few weeks ago. Please comment your additional plugins and update CodeArt and then uncomment your additional plugins. It should work If it doesn't please reopen issue.
