### ISSUE TITLE
Check for chocolatey already installed is missing

### ISSUE THREAD

**Issue by aniketgm** [artart222/CodeArt#62]
On Windows, I had chocolatey already installed. The windows.ps1 script was reinstalling chocolatey. I think a check for chocolatey is missing in there.

**Comment by Ashraf-wan** [comment]
i will try to make the feature and make a pull request

**Comment by Ashraf-wan** [comment]
this repo is dead already just go to my fork https://github.com/Ashraf-wan/CodeArt

**Comment by aniketgm** [comment]
> this repo is dead already just go to my fork https://github.com/Ashraf-wan/CodeArt

Yes, seems right. 2 years and no reply from the repo owner/any of major contributors. nothing. it is dead it seems. Closing this issue here.

For others looking for a solution can check [Ashraf-wan/CodeArt](https://github.com/Ashraf-wan/CodeArt) as mentioned by him above.

**Comment by artart222** [comment]
Hi, I think I said this earlier in another issue but I'm not sure. I have university entrance exam in 3 month and I'm in school from 7am to 9pm. After the entrance exams I will be available again and I will work on my repos

**Comment by aniketgm** [comment]
oh. then no need to take pressure on this right now. Focus on your exams. Finish that first then this can be checked later.
Coming from a country where education is getting destroyed. I firmly believe completing the education.

I would suggest writing on the README that you might be busy for a while and ask the contributors for help.
I can understand not dealing with any New/Old issue. However, I also see PRs pending. Maybe you could've checked those at least once in a while. But anyways. all the best for your exams.

**Comment by Ashraf-wan** [comment]
Good luck on your exam too
