### ISSUE TITLE
Will this completely wipe out my current init.vim file?

### ISSUE THREAD

**Issue by Vaimer9** [artart222/CodeArt#7]
I want to install this but also be able to go back to my own nvim if I don't like it, haven't installed yet just asking.

**Comment by artart222** [comment]
If you are in linux it will make backup of ~/.config/nvim it must do same thing in macOS but I didn't test it but if you want to install it on windows you must make backup by your self and in addition :CodeArtUpdate command in CodeArt will replace this repo configs directory with ~/.config/nvim
