### ISSUE TITLE
get this error when booted

### ISSUE THREAD

**Issue by Vaimer9** [artart222/CodeArt#8]
![image](https://user-images.githubusercontent.com/81609819/139661446-c61faa93-d4fa-4bd0-be0c-d0b49417352b.png)

**Comment by Vaimer9** [comment]
on Kubuntu, no wsl

**Comment by artart222** [comment]
After installing you must open NeoVim and run :PackerSync command

**Comment by Vaimer9** [comment]
thanks lol

**Comment by artart222** [comment]
You're welcome
